### ISSUE TITLE
Workflow/branching model

### ISSUE THREAD

**Issue by cmhughes** [michal-h21/tex4ht-doc#1]
Hi Michael, 
Thanks very much for creating this repository; I'm 'watching' it, and have forked it as well. I certainly hope to contribute to the project as time goes on.

I wondered what kind of work flow you'd like to use for the project. Specifically, I wondered what you think about having a `develop` branch to which pull requests are submitted, so that `master` always contains the most up to date version? I've seen this approach to be quite effective on other projects, but perhaps it wouldn't be appropriate here?

Best
Chris (cmhughes)

**Comment by michal-h21** [comment]
Hi Chris,

Thanks for your comment and I hope you will be able to contribute. I am fine with this work flow, it seems good for projects with more contributors.

I've updated the info in README, because I forgot that not yet released version of `make4ht` is necessary for the compilation. I've just uploaded it to CTAN, but it will be available only in TL 2018.

**Comment by cmhughes** [comment]
Great, many thanks, Michal. I'll close this for now.

My apologies for putting an extra 'e' in your name.
